
import type { Event, Sponsor, ScheduleItem, Update } from "@/lib/types";

export const events: Event[] = [
  {
    id: "evt-001",
    title: "Code Combat",
    category: "Programming & Development",
    description: "An intense coding competition to solve algorithmic challenges against the clock.",
    image: "https://placehold.co/600x400.png",
    date: "Day 1",
    time: "10:00 AM - 1:00 PM",
    rules: ["Solo participation only.", "Standard library only.", "Plagiarism leads to disqualification."],
    prizes: ["1st: Gaming Keyboard", "2nd: 1-year GitHub Pro", "3rd: Swag Pack"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-002",
    title: "Hackathon: AI for Good",
    category: "Programming & Development",
    description: "A 24-hour hackathon to build innovative solutions for social challenges using AI.",
    image: "https://placehold.co/600x400.png",
    date: "Day 1-2",
    time: "Starts 11:00 AM",
    rules: ["Teams of 2-4.", "Must use at least one sponsoring AI API.", "Code must be pushed to a public repo."],
    prizes: ["1st: $1000 Cash", "2nd: Cloud Credits", "3rd: Smart Home Devices"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-003",
    title: "Robo-Wars",
    category: "Hardware & Innovation",
    description: "Design, build, and battle your custom-built robot in a head-to-head combat tournament.",
    image: "https://placehold.co/600x400.png",
    date: "Day 2",
    time: "11:00 AM - 4:00 PM",
    rules: ["Weight limit: 15kg.", "No flammable weapons.", "Remote-controlled operation only."],
    prizes: ["Winner: 3D Printer", "Runner-up: Advanced Robotics Kit"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-004",
    title: "UI/UX Design Challenge",
    category: "Design & Creativity",
    description: "Redesign a popular application's interface to improve usability and aesthetics.",
    image: "https://placehold.co/600x400.png",
    date: "Day 1",
    time: "2:00 PM - 5:00 PM",
    rules: ["Submit a high-fidelity prototype.", "Must include a design document explaining choices.", "Use of Figma or Adobe XD."],
    prizes: ["1st: 1-year Adobe CC Subscription", "2nd: Wacom Tablet"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-005",
    title: "Digital Art Contest",
    category: "Creative Arts",
    description: "Create a stunning piece of digital art based on the theme 'Future of Technology'.",
    image: "https://placehold.co/600x400.png",
    date: "Day 1-2",
    time: "Submission by Day 2, 5 PM",
    rules: ["Must be original artwork.", "Any digital medium is allowed.", "Submit in high resolution."],
    prizes: ["1st: Drawing Tablet", "2nd: Art Prints Voucher"],
    type: "non-technical",
    status: "upcoming",
  },
  {
    id: "evt-006",
    title: "Tech Trivia Night",
    category: "Interactive Competitions",
    description: "Test your knowledge on technology, sci-fi, and geek culture in a fun quiz night.",
    image: "https://placehold.co/600x400.png",
    date: "Day 1",
    time: "6:00 PM - 8:00 PM",
    rules: ["Teams of up to 5.", "No use of mobile phones."],
    prizes: ["Winning Team: Exclusive T-Shirts & Bragging Rights"],
    type: "non-technical",
    status: "upcoming",
  },
  {
    id: "evt-007",
    title: "E-Sports Tournament: Valorant",
    category: "Entertainment",
    description: "Compete in a 5v5 Valorant tournament and prove your team's tactical prowess.",
    image: "https://placehold.co/600x400.png",
    date: "Day 2",
    time: "10:00 AM - 6:00 PM",
    rules: ["Pre-registered teams only.", "Standard competitive rules apply.", "Bring your own peripherals."],
    prizes: ["1st: Gaming Headsets for all team members", "2nd: Steam Vouchers"],
    type: "non-technical",
    status: "upcoming",
  },
  {
    id: "evt-008",
    title: "DJ Night ft. DJ Nucleya",
    category: "Cultural Fest",
    description: "End the fest on a high note with an electrifying performance by a world-renowned DJ.",
    image: "https://placehold.co/600x400.png",
    date: "Day 2",
    time: "9:00 PM onwards",
    rules: ["Entry included with fest pass.", "Be respectful and have fun!"],
    prizes: ["Best Dancer: A lifetime of memories"],
    type: "cultural",
    status: "upcoming",
  }
];


export const sponsors: Sponsor[] = [
  { id: "1", name: "TechCorp", logo: "https://placehold.co/200x100.png", url: "#" },
  { id: "2", name: "Innovate Inc.", logo: "https://placehold.co/200x100.png", url: "#" },
  { id: "3", name: "Future Systems", logo: "https://placehold.co/200x100.png", url: "#" },
  { id: "4", name: "Cyber Solutions", logo: "https://placehold.co/200x100.png", url: "#" },
  { id: "5", name: "Dev Tools", logo: "https://placehold.co/200x100.png", url: "#" },
  { id: "6", name: "Quantum Leap", logo: "https://placehold.co/200x100.png", url: "#" },
];

export const schedule: ScheduleItem[] = [
  {
    time: "Day 1 - 09:00 AM",
    title: "Opening Ceremony",
    description: "Kick-off speech and introduction to TechVista 2025.",
  },
  {
    time: "Day 1 - 10:00 AM",
    title: "Technical & Non-Technical Events Begin",
    description: "First wave of competitions and workshops starts across the campus.",
  },
  {
    time: "Day 1 - 07:00 PM",
    title: "Cultural Fest Kick-off",
    description: "The evening comes alive with music, dance, and performances.",
  },
  {
    time: "Day 2 - 10:00 AM",
    title: "Day 2 Events Commence",
    description: "The second day of exciting technical and non-technical events begins.",
  },
  {
    time: "Day 2 - 07:00 PM",
    title: "Prize Distribution",
    description: "Recognizing the winners of the various competitions.",
  },
  {
    time: "Day 2 - 09:00 PM",
    title: "Closing Ceremony & DJ Night",
    description: "Concluding the fest with awards and a grand celebration.",
  },
];
