
import type { Event, Sponsor, ScheduleItem, Update, GalleryImage } from "@/lib/types";

export const events: Event[] = [
  // Day 1 Technical
  {
    id: "evt-001",
    title: "Code Combat (Hackathon)",
    category: "Programming & Development",
    description: "6-hour coding marathon where teams solve real-world problems.",
    image: "https://picsum.photos/600/400?random=1",
    date: "Day 1",
    time: "9:00 AM – 3:00 PM",
    rules: ["Max 3 members per team", "Plagiarism not allowed", "Open internet resources"],
    prizes: ["1st Place: Trophy + Certificates", "2nd Place: Medals + Certificates"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-002",
    title: "Debugging Arena",
    category: "Programming & Development",
    description: "Spot and fix errors in pre-written buggy codes (C/C++/Python).",
    image: "https://picsum.photos/600/400?random=2",
    date: "Day 1",
    time: "11:00 AM – 1:00 PM",
    rules: ["Individual participation", "Fastest debugging wins"],
    prizes: ["Winner: Certificate of Excellence", "Runner-up: Certificate"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-003",
    title: "Tech Quiz",
    category: "Interactive Competitions",
    description: "Quiz based on programming, tech trends, AI, cybersecurity, blockchain.",
    image: "https://picsum.photos/600/400?random=3",
    date: "Day 1",
    time: "2:30 PM – 4:00 PM",
    rules: ["Teams of 2", "No phones allowed"],
    prizes: ["Winners: Tech Goodies", "Runners-up: Books Voucher"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-004",
    title: "Robo Wars",
    category: "Hardware & Innovation",
    description: "Robots battle in an arena.",
    image: "https://picsum.photos/600/400?random=4",
    date: "Day 1",
    time: "4:00 PM – 6:00 PM",
    rules: ["Only self-built bots", "Safety checks mandatory", "Weight < 10kg"],
    prizes: ["Champion: Robotics Kit", "Runner-up: Electronic components"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-005",
    title: "Paper Presentation",
    category: "Design & Creativity",
    description: "Students present innovative papers on AI/ML/Blockchain/IoT.",
    image: "https://picsum.photos/600/400?random=5",
    date: "Day 1",
    time: "3:00 PM – 5:00 PM",
    rules: ["Solo or duo", "Max 10 slides", "8 min presentation + 2 min Q&A"],
    prizes: ["Best Paper Award", "Honorable Mention"],
    type: "technical",
    status: "upcoming",
  },
  // Day 1 Non-Technical
  {
    id: "evt-006",
    title: "Treasure Hunt",
    category: "Interactive Competitions",
    description: "Solve riddles & clues spread across campus.",
    image: "https://picsum.photos/600/400?random=6",
    date: "Day 1",
    time: "10:00 AM – 12:00 PM",
    rules: ["Teams of 4", "Mobile phones allowed for scanning QR clues"],
    prizes: ["Winning Team: Gift Vouchers", "Runner-up: Surprise gifts"],
    type: "non-technical",
    status: "upcoming",
  },
  {
    id: "evt-007",
    title: "Photography Contest",
    category: "Creative Arts",
    description: "Capture “Life @ Techfest” in your own lens.",
    image: "https://picsum.photos/600/400?random=7",
    date: "Day 1",
    time: "12:00 PM – 2:00 PM",
    rules: ["Solo participation", "Editing allowed but original RAW required"],
    prizes: ["Best Photo: Framed Print + Certificate", "Runner-up: Certificate"],
    type: "non-technical",
    status: "upcoming",
  },
  {
    id: "evt-008",
    title: "Minute to Win It",
    category: "Entertainment",
    description: "Quick one-minute challenges (cups, balance, riddles).",
    image: "https://picsum.photos/600/400?random=8",
    date: "Day 1",
    time: "2:00 PM – 4:00 PM",
    rules: ["Individual", "No retries", "Top scorers advance"],
    prizes: ["Fun hampers for winners"],
    type: "non-technical",
    status: "upcoming",
  },
  {
    id: "evt-009",
    title: "Open Mic & Standup",
    category: "Cultural Fest",
    description: "Students perform standup comedy, poetry, storytelling.",
    image: "https://picsum.photos/600/400?random=9",
    date: "Day 1",
    time: "4:00 PM – 6:00 PM",
    rules: ["Max 5 mins", "No offensive content"],
    prizes: ["Audience Choice Award"],
    type: "cultural",
    status: "upcoming",
  },
  {
    id: "evt-010",
    title: "LAN Gaming",
    category: "Entertainment",
    description: "Gaming tournament for enthusiasts (BGMI, Valorant, FIFA).",
    image: "https://picsum.photos/600/400?random=10",
    date: "Day 1",
    time: "6:00 PM – 9:00 PM",
    rules: ["Solo or squad depending on the game", "Knockout format"],
    prizes: ["Gaming peripherals for winners"],
    type: "non-technical",
    status: "upcoming",
  },
  // Day 2 Technical
  {
    id: "evt-011",
    title: "App Development Challenge",
    category: "Programming & Development",
    description: "Build a working prototype in 5 hours.",
    image: "https://picsum.photos/600/400?random=11",
    date: "Day 2",
    time: "9:00 AM – 2:00 PM",
    rules: ["Teams of 3", "Can use any framework"],
    prizes: ["1st Place: Internship Opportunity", "2nd Place: Tech gadgets"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-012",
    title: "Circuitrix (Circuit Design)",
    category: "Hardware & Innovation",
    description: "Design and simulate electronic circuits.",
    image: "https://picsum.photos/600/400?random=12",
    date: "Day 2",
    time: "11:00 AM – 1:00 PM",
    rules: ["Individual", "Components and simulator provided"],
    prizes: ["Winner: Digital Multimeter Kit", "Runner-up: Certificate"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-013",
    title: "Capture The Flag (CTF)",
    category: "Programming & Development",
    description: "Solve hacking/security challenges to “capture flags.”",
    image: "https://picsum.photos/600/400?random=13",
    date: "Day 2",
    time: "1:30 PM – 5:30 PM",
    rules: ["Teams of 2", "Laptops mandatory", "Internet allowed"],
    prizes: ["Winner: Premium Cybersecurity Course Subscription"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-014",
    title: "Data Science Challenge",
    category: "Programming & Development",
    description: "Analyze datasets and present insights/ML models.",
    image: "https://picsum.photos/600/400?random=14",
    date: "Day 2",
    time: "2:00 PM – 6:00 PM",
    rules: ["Teams of 2", "Python (pandas/sklearn) allowed"],
    prizes: ["Winner: DataCamp Subscription", "Runner-up: Certificate"],
    type: "technical",
    status: "upcoming",
  },
  {
    id: "evt-015",
    title: "Drone Racing",
    category: "Hardware & Innovation",
    description: "Time-trial drone flying competition.",
    image: "https://picsum.photos/600/400?random=15",
    date: "Day 2",
    time: "5:00 PM – 7:00 PM",
    rules: ["BYODrones", "Safety helmets required"],
    prizes: ["Fastest Pilot: Mini Racing Drone", "Runner-up: Spare parts"],
    type: "technical",
    status: "upcoming",
  },
  // Day 2 Non-Technical
  {
    id: "evt-016",
    title: "Ad-Mad Show",
    category: "Creative Arts",
    description: "Create funny & creative ads for random objects.",
    image: "https://picsum.photos/600/400?random=16",
    date: "Day 2",
    time: "10:00 AM – 12:00 PM",
    rules: ["Teams of 3", "Max 2 mins"],
    prizes: ["Most Creative Team Award"],
    type: "non-technical",
    status: "upcoming",
  },
  {
    id: "evt-017",
    title: "Debate Competition",
    category: "Interactive Competitions",
    description: "Face-off on trending topics in tech, politics, society.",
    image: "https://picsum.photos/600/400?random=17",
    date: "Day 2",
    time: "11:30 AM – 1:30 PM",
    rules: ["Teams of 2", "4 mins per speaker"],
    prizes: ["Best Orator Award", "Runner-up: Certificate"],
    type: "non-technical",
    status: "upcoming",
  },
  {
    id: "evt-018",
    title: "Talent Hunt",
    category: "Cultural Fest",
    description: "Cultural showcase (Dance, Music, Drama).",
    image: "https://picsum.photos/600/400?random=18",
    date: "Day 2",
    time: "2:00 PM – 5:00 PM",
    rules: ["Solo/Group", "Max 5 mins"],
    prizes: ["Performer of the Fest Award"],
    type: "cultural",
    status: "upcoming",
  },
  {
    id: "evt-019",
    title: "Short Film Contest",
    category: "Creative Arts",
    description: "Submit a 3–5 min film on “Technology for Humanity.”",
    image: "https://picsum.photos/600/400?random=19",
    date: "Day 2",
    time: "3:00 PM – 6:00 PM",
    rules: ["Teams of up to 5", "Any genre"],
    prizes: ["Best Film Award", "Certificate of Participation"],
    type: "non-technical",
    status: "upcoming",
  },
  {
    id: "evt-020",
    title: "DJ Night / Cultural Evening",
    category: "Cultural Fest",
    description: "Closing cultural + music night.",
    image: "https://picsum.photos/600/400?random=20",
    date: "Day 2",
    time: "7:00 PM – 9:00 PM",
    rules: ["Open to all registered participants"],
    prizes: ["Good vibes and lasting memories"],
    type: "cultural",
    status: "upcoming",
  },
];


export const sponsors: Sponsor[] = [
  { id: "1", name: "TechCorp", logo: "https://picsum.photos/200/100?random=21", url: "#" },
  { id: "2", name: "Innovate Inc.", logo: "https://picsum.photos/200/100?random=22", url: "#" },
  { id: "3", name: "Future Systems", logo: "https://picsum.photos/200/100?random=23", url: "#" },
  { id: "4", name: "Cyber Solutions", logo: "https://picsum.photos/200/100?random=24", url: "#" },
  { id: "5", name: "Dev Tools", logo: "https://picsum.photos/200/100?random=25", url: "#" },
  { id: "6", name: "Quantum Leap", logo: "https://picsum.photos/200/100?random=26", url: "#" },
];

export const schedule: ScheduleItem[] = [
    // Day 1
    { time: "Day 1 - 09:00 AM", title: "Code Combat (Hackathon)", description: "6-hour coding marathon." },
    { time: "Day 1 - 10:00 AM", title: "Treasure Hunt", description: "Solve riddles & clues across campus." },
    { time: "Day 1 - 11:00 AM", title: "Debugging Arena", description: "Spot and fix errors in buggy code." },
    { time: "Day 1 - 12:00 PM", title: "Photography Contest", description: "Capture “Life @ Techfest”." },
    { time: "Day 1 - 02:00 PM", title: "Minute to Win It", description: "Quick one-minute challenges." },
    { time: "Day 1 - 02:30 PM", title: "Tech Quiz", description: "Quiz on tech trends, AI, and more." },
    { time: "Day 1 - 03:00 PM", title: "Paper Presentation", description: "Present papers on AI/ML/Blockchain." },
    { time: "Day 1 - 04:00 PM", title: "Robo Wars", description: "Robots battle in an arena." },
    { time: "Day 1 - 04:00 PM", title: "Open Mic & Standup", description: "Comedy, poetry, storytelling." },
    { time: "Day 1 - 06:00 PM", title: "LAN Gaming", description: "BGMI, Valorant, FIFA tournament." },
    // Day 2
    { time: "Day 2 - 09:00 AM", title: "App Development Challenge", description: "Build a working prototype in 5 hours." },
    { time: "Day 2 - 10:00 AM", title: "Ad-Mad Show", description: "Create funny & creative ads." },
    { time: "Day 2 - 11:00 AM", title: "Circuitrix", description: "Design and simulate electronic circuits." },
    { time: "Day 2 - 11:30 AM", title: "Debate Competition", description: "Face-off on trending topics." },
    { time: "Day 2 - 01:30 PM", title: "Capture The Flag (CTF)", description: "Solve hacking/security challenges." },
    { time: "Day 2 - 02:00 PM", title: "Data Science Challenge", description: "Analyze datasets and present insights." },
    { time: "Day 2 - 02:00 PM", title: "Talent Hunt", description: "Cultural showcase of dance, music, drama." },
    { time: "Day 2 - 03:00 PM", title: "Short Film Contest", description: "Submit a 3–5 min film." },
    { time: "Day 2 - 05:00 PM", title: "Drone Racing", description: "Time-trial drone flying competition." },
    { time: "Day 2 - 07:00 PM", title: "DJ Night / Cultural Evening", description: "Closing cultural + music night." },
];

export const galleryImages: GalleryImage[] = [
    { src: "https://picsum.photos/400/300?random=31", alt: "Previous fest photo 1" },
    { src: "https://picsum.photos/400/300?random=32", alt: "Previous fest photo 2" },
    { src: "https://picsum.photos/400/300?random=33", alt: "Previous fest photo 3" },
    { src: "https://picsum.photos/400/300?random=34", alt: "Previous fest photo 4" },
    { src: "https://picsum.photos/400/300?random=35", alt: "Previous fest photo 5" },
    { src: "https://picsum.photos/400/300?random=36", alt: "Previous fest photo 6" },
    { src: "https://picsum.photos/400/300?random=37", alt: "Previous fest photo 7" },
    { src: "https://picsum.photos/400/300?random=38", alt: "Previous fest photo 8" },
]
